apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-management
  #Add a strategy: type: ...
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: mvn-jdk17
          image: antoninlampin/mvn-jdk17:2
          ports:
            - containerPort: 8080